global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'clinic-api'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['clinic-api:9999']

rule_files:
  - "recording-rules.yml"
  - "alert-rules.yml"          # (Day 3)

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093